--- Provides words used for Hangman games.
local WordList = {}

-- The list of words that can be guessed.
local words = {
  'Bank',
  'Brut',
  'Bund',
  'Echo',
  'Geld',
  'Hase',
  'Hohl',
  'Lang',
  'Last',
  'Netz',
  'Puls',
  'Shag',
  'Topf',
  'Wale',
  'Blatt',
  'Debug',
  'Donut',
  'Gutsy',
  'Intim',
  'Nackt',
  'Offen',
  'Phase',
  'Recht',
  'Reich',
  'Stadt',
  'Sumpf',
  'Virus',
  'Waffe',
  'Bereit',
  'Billig',
  'Donner',
  'Dreist',
  'Eifrig',
  'Erotik',
  'Finden',
  'Flocke',
  'Gefahr',
  'Gratis',
  'Hangar',
  'Hinten',
  'Karibu',
  'Kreide',
  'Krippe',
  'Leblos',
  'Lecker',
  'Leguan',
  'Massiv',
  'Munter',
  'Profil',
  'Purpur',
  'Rahmen',
  'Riesen',
  'Stimme',
  'Testen',
  'Teufel',
  'Tragen',
  'Trauma',
  'Unhold',
  'Wollen',
  'Angriff',
  'Blutend',
  'Fahrrad',
  'Gitarre',
  'Hybride',
  'Jubelnd',
  'Kompakt',
  'Kratzig',
  'Mischer',
  'Prahlen',
  'Riechen',
  'Scarify',
  'Skurril',
  'Starten',
  'Anregend',
  'Aufladen',
  'Batterie',
  'Blendend',
  'Friedhof',
  'Getreide',
  'Kaugummi',
  'Ofenrohr',
  'Programm',
  'Schulden',
  'Steckend',
  'Angeblich',
  'Aufgeregt',
  'Begleiten',
  'Effizient',
  'Fließend',
  'Gehorchen',
  'Identisch',
  'Kaninchen',
  'Nachgeben',
  'Politisch',
  'Versuchen',
  'Wohltuend',
  'Alternativ',
  'Amoralisch',
  'Apokalypse',
  'Augenbinde',
  'Babysitter',
  'Beleuchten',
  'Evakuieren',
  'Großartig',
  'Ordentlich',
  'Schleichen',
  'Spirituell',
  'Steppdecke',
  'Streicheln',
  'Abwesenheit',
  'Einstellung',
  'Geometrisch',
  'Meerrettich',
  'Offenlegung',
  'Richtlinien',
  'Temperament',
  'Unglaublich',
  'Versprechen',
  'Absorbierend',
  'Adsorbierbar',
  'Alphabetisch',
  'Gewerkschaft',
  'Haferflocken',
  'Hoffnungslos',
  'Konsultieren',
  'Organisieren',
  'Unvollkommen',
  'Demonstration',
  'Fadenscheinig',
  'Pessimistisch',
  'Furchterregend',
  'Sommersprossig',
  'Transformieren',
  'Zusammenpassen',
  'Wiederverwenden',
}

--- Picks a random word from the word list.
---@return string? word A random word or `nil` if the list is empty.
---@return string? err An error message if the list is empty.
function WordList.random()
  if #words == 0 then return nil, 'The word list is empty!' end

  return words[math.random(#words)]
end

return WordList
